[package]
name = "tentacle"
version = "0.1.0"
authors = ["tkaden4 <thomas.kaden4@outlook.com>"]

[dependencies]
semver="0.9.0"
serde="*"
serde_derive="*"
serde_json="1.0"
pnet="*"
nix="*"
clap="*"
ansi_term="*"
matches="*"
